version: 2
jobs:
  build:
    docker:
      - image: clojure:alpine
    working_directory: ~/books
    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: apk update && apk upgrade && apk add mongodb
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
  test:
    docker:
      - image: clojure:alpine
    steps:
      - checkout
      - run: lein test
  deploy:
    machine: true
    working_directory: ~/books
    steps:
      - checkout
      - run:
          name: "First copy the files"
          command: scp -r . circleci@valerauko.net:books
      - run:
          name: "Build Docker image"
          command: ssh circleci@valerauko.net "cd ~/books; docker build -t books ."
      - run:
          name: "Set up volumes and ports"
          command: ssh circleci@valerauko.net "cd ~/books; docker run -itd --name books -v \"$(pwd)\":/var/www -v \"$(pwd)/data\":/data/db -p 1340:3000 books"
      - run:
          name: "Finally start the server"
          commend: ssh circleci@valerauko.net "cd ~/books; docker exec -it books lein run"

workflows:
  version: 2
  core_flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
