version: 2.1

executors:
  tester:
    docker:
      - image: clojure:lein-alpine
      - image: mongo:3.6-xenial
    working_directory: ~/books
    environment:
      LEIN_ROOT: "true"
      MONGO_URL: mongodb://localhost/local
      JVM_OPTS: -Xmx3200m

commands:
  lein-deps:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
  set-version:
    steps:
      - run: echo "export BOOKS_VERSION=$(head -n 1 project.clj | tr -cd '[[:digit:]\.]')" >> $BASH_ENV

jobs:
  test:
    executor: tester
    steps:
      - checkout
      - lein-deps
      - run: lein test

  build:
    docker:
      - image: clojure:lein-alpine
    steps:
      - checkout
      - lein-deps
      - run: lein uberjar
      - persist_to_workspace:
          root: .
          paths:
            - target/books-[0-9].[0-9].[0-9].jar

  docker-push:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - set-version
      - run: docker build -t valerauko/books:$BOOKS_VERSION .
      - run: docker push valerauko/books:$BOOKS_VERSION

workflows:
  version: 2
  core_flow:
    jobs:
      - test
      - build:
          requires:
            - test
          # filters:
          #   branches:
          #     only: master
      - hold:
          type: approval
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
      - docker-push:
          requires:
            - hold
          # filters:
          #   branches:
          #     only: master
